[build]
rustflags = "--cfg r2r__rosgraph_msgs__msg__Clock"

[env]
# TODO: Find better way than this to make colcon happy with opencv
# TODO: Append include path for x86
PKG_CONFIG_PATH = "/usr/lib/aarch64-linux-gnu/pkgconfig"
